### ISSUE TITLE
Consider changing *03_pivot_root* to use a loopback filesystem so that *pivot_root* doesn't fail

### ISSUE THREAD

**Issue by nukemberg** [Fewbytes/rubber-docker#15]
Consider changing _03_pivot_root_ to use a loopback filesystem (extract the image to a new loopback ext4 fs) so that _pivot_root_ doesn't fail - this confuses people

wdyt @natict ?

**Comment by natict** [comment]
sounds good, but need to re-think the workshop flow

**Comment by nukemberg** [comment]
same flow. but instead of having people fail step 03 we will add cow to resolve slow bootstrap
