### ISSUE TITLE
Run rd.py via Vagrantfile

### ISSUE THREAD

**Issue by cmeury** [Fewbytes/rubber-docker#36]
To run `rd.py` on the vagrant box, I had to specify the path:

```
export PYTHONPATH=/usr/lib/python2.7/dist-packages:/workshop/rubber-docker
```

Not sure what the best way to configure this via the Vagrantfile

**Comment by natict** [comment]
The boxcutter images are down. After switching to official ubuntu image I wasn't able to reproduce the issue. I know this is an old one, but do you remember if you did anything other than to run `rd.py` ?

**Comment by cmeury** [comment]
Uhhh, no idea, sorry. :)
